### ISSUE TITLE
Overhead in centos.yml

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-repo-collabora-code#2]
### Type of Report

Enhancement

### Actual behaviour

The following code is present in centos.yml

```
- name: set fact for task names to Add
  set_fact:
    wtd_repo_collabora_code_task_name: "Add"
  when: wtd_repo_collabora_code_state == "present"

- name: set fact for task names to Remove
  set_fact:
    wtd_repo_collabora_code_task_name: "Remove"
when: wtd_repo_collabora_code_state != "present"
```

As far as I can see, it is only used some line later

```
- name: "{{ wtd_repo_collabora_code_task_name }} key for repository Collabora Online CODE"
...
- name: "{{ wtd_repo_collabora_code_task_name }} repository Collabora Online CODE"
```
Seems like a lot of overhead for a simple wording.

### Expected behaviour

Remove the wtd_repo_collabora_code_task_name
Change the lines to something like
```
- name: Set repository key for Collabora Online CODE to "{{ wtd_repo_collabora_code_state }}"
...
- name: Set repository for Collabora Online CODE to "{{ wtd_repo_collabora_code_state }}"
```

Would be much easier to read ( code wise ) and reduce the overhead of setting facts.
